
create table ACCOUNT (
	ACCOUNT_ID INTEGER NOT NULL AUTO_INCREMENT COMMENT 'アカウントID',
	EMPLOYEE_NO INTEGER NOT NULL COMMENT '社員番号',
	EMAIL_ADDRESS VARCHAR(129) NOT NULL COMMENT 'メールアドレス',
	PASSWORD VARCHAR(64) NOT NULL COMMENT 'パスワード:暗号化済みパスワード',

	-- COMMON COLUMNS
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時:共通カラム',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時:共通カラム',

	PRIMARY KEY (ACCOUNT_ID)
) COMMENT = 'アカウント'
;

create table ACCOUNT_PROFILE (
	ACCOUNT_PROFILE_ID INTEGER NOT NULL AUTO_INCREMENT,
	ACCOUNT_ID INTEGER NOT NULL COMMENT 'アカウントID',
	ACCOUNT_NAME VARCHAR(50) NOT NULL COMMENT '氏名',

	-- COMMON COLUMNS
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時:共通カラム',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時:共通カラム',

	PRIMARY KEY(ACCOUNT_PROFILE_ID),
	UNIQUE(ACCOUNT_ID)
)
;

create table LOCATION(
	LOCATION_ID INTEGER AUTO_INCREMENT NOT NULL,
	LOCATION_NAME VARCHAR(64) NOT NULL,

	PRIMARY KEY(LOCATION_ID)
) COMMENT = '勤務地'
;

create table COMMUNITY(
	COMMUNITY_ID INTEGER NOT NULL AUTO_INCREMENT,
	COMMUNITY_NAME VARCHAR(128) NOT NULL,
	ACCOUNT_ID INTEGER NOT NULL COMMENT 'アカウントID:代表者アカウントID',

	-- COMMON COLUMNS
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時:共通カラム',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時:共通カラム',

	PRIMARY KEY(COMMUNITY_ID)
) COMMENT = 'ユーザコミュニティ'
;

create table USER_GROUPING (
	USER_GROUPING_ID INTEGER(10) AUTO_INCREMENT NOT NULL,
	ACCOUNT_ID INTEGER NOT NULL COMMENT 'アカウントID:',
	COMMUNITY_ID INTEGER NOT NULL COMMENT 'コミュニティID',

	-- COMMON COLUMNS
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時:共通カラム',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時:共通カラム',

	PRIMARY KEY(USER_GROUPING_ID)
)COMMENT = 'コミュニティ所属'
;

-- alter table ACCOUNT add constraint FK_ACCOUNT_LOCATION foreign key(LOCATION_ID) references LOCATION(LOCATION_ID);
alter table ACCOUNT_PROFILE add constraint FK_ACCOUNT_PROFILE_ACCOUNT foreign key(ACCOUNT_ID) references ACCOUNT(ACCOUNT_ID);
alter table USER_GROUPING add constraint FK_USER_GROUPING_MEMBER foreign key (ACCOUNT_ID) references ACCOUNT(ACCOUNT_ID);
alter table USER_GROUPING add constraint FK_USER_GROUPING_COMMUNITY foreign key (COMMUNITY_ID) references COMMUNITY(COMMUNITY_ID);
